# Generated by Django 5.1.15 on 2026-08-31 11:17

import django.db.models.deletion
import organization.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=organization.models.company_logo_upload_path)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('calendar', models.CharField(choices=[('BS', 'Bikram Sambat (Shrawan–Ashad)'), ('AD', 'Gregorian (January–December)')], default='BS', help_text="The calendar this company's fiscal year, payslips and leave entitlements follow.", max_length=4)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], help_text="Month the financial year opens on, in the calendar above. Leave empty to use that calendar's own year — Shrawan for Bikram Sambat, January for Gregorian.", null=True)),
                ('unpaid_break_minutes', models.PositiveIntegerField(default=60, help_text='Minutes of the office span that are not paid — lunch, usually.')),
                ('office_start_time', models.TimeField(blank=True, help_text='When the office opens. Used to judge lateness for employees with no shift assigned. Leave empty and they are never marked late.', null=True)),
                ('office_end_time', models.TimeField(blank=True, help_text='When the office closes. Recorded alongside the opening time.', null=True)),
                ('office_grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after opening before somebody counts as late.')),
                ('retirement_scheme', models.CharField(blank=True, choices=[('ssf', 'Social Security Fund'), ('pf', 'Provident Fund')], help_text='Which retirement fund this company is enrolled in. SSF and PF are alternatives — running both would double-deduct. Leave empty if neither.', max_length=10)),
                ('retirement_paused', models.BooleanField(default=False, help_text='Stop deducting for the chosen fund without changing which fund it is. Existing contribution history is kept.')),
                ('offers_cit', models.BooleanField(default=False, help_text='Employees may contribute to the Citizen Investment Trust through payroll.')),
                ('provides_gratuity', models.BooleanField(default=False, help_text='Employer-funded gratuity. Not applicable on SSF, which already covers it.')),
                ('working_days', models.JSONField(default=list, help_text='ISO weekday numbers (1=Monday..7=Sunday) that count as working days.', validators=[organization.models.validate_iso_weekdays])),
                ('pay_basis', models.CharField(choices=[('calendar', 'Calendar month'), ('working_days', 'Working days')], default='calendar', help_text='How one day of pay is valued when absence is deducted. Calendar month divides by the days in the month; working days divides by the days this company works, which makes each absence cost more.', max_length=20)),
                ('payroll_prorate', models.BooleanField(default=True, help_text='When on, a payslip is prorated by the number of calendar days the employee is actually payable in the month (driven by salary-structure effective date, join date and last working date). When off, any active structure pays the full month regardless of when it started.')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Multiplier applied to the ordinary hourly rate for approved overtime. Verify against the current Labour Act before going live.', max_digits=4)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SetupSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_key', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['check_key'],
            },
        ),
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.BinaryField(blank=True, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False, help_text='Use these settings instead of the platform default.')),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_self', 'Pending Self-Assessment'), ('pending_manager', 'Pending Manager Review'), ('completed', 'Completed')], default='pending_self', max_length=20)),
                ('self_assessment', models.TextField(blank=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_assessment', models.TextField(blank=True)),
                ('manager_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manager_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organization.reviewcycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'employee'), name='unique_cycle_employee_review')],
            },
        ),
    ]
