# Generated by Django 5.1.15 on 2026-09-01 17:22

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('meeting', 'Meeting'), ('board', 'Board meeting'), ('agm', 'General meeting'), ('ceremony', 'Ceremony'), ('training', 'Training'), ('drill', 'Drill / safety exercise'), ('inspection', 'Inspection / audit'), ('public', 'Public / community'), ('site_visit', 'Site visit'), ('other', 'Other')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=20)),
                ('subject_matter', models.CharField(blank=True, help_text='What it is about, in one line.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('outcome', models.TextField(blank=True, help_text='Minutes, decisions, what came of it.')),
                ('company', models.ForeignKey(blank=True, help_text='Which group company this belongs to, where it belongs to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_events', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=events.models.event_attachment_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_code', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('attendee', 'Attendee'), ('chair', 'Chair'), ('speaker', 'Speaker'), ('organiser', 'Organiser'), ('guest', 'Guest'), ('observer', 'Observer')], default='attendee', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('attended', models.BooleanField(blank=True, help_text='Left empty until the event has happened.', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_appearances', to='employees.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='events.event')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_even_starts__b01102_idx'),
        ),
    ]
