# Generated by Django 5.1.15 on 2026-08-31 11:17

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_tag', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='other', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'In maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateField()),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=assets.models.asset_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text="What this shows — 'serial plate', 'scratch on lid at handover'.", max_length=200)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
