# Generated by Django 5.1.15 on 2026-09-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('acquired', 'Acquired'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('maintenance', 'Sent for maintenance'), ('repaired', 'Back from maintenance'), ('status', 'Status changed'), ('note', 'Note'), ('retired', 'Retired'), ('lost', 'Reported lost')], default='note', max_length=20)),
                ('from_value', models.CharField(blank=True, max_length=60)),
                ('to_value', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('occurred_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at', '-id'],
            },
        ),
    ]
