# Generated by Django 5.1.15 on 2026-09-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_primary_company_one_primary_company'),
        ('notifications', '0002_meeting_agenda_decisions_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_minutes', to='companies.company'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='minute_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MinutesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_serial', models.PositiveIntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_counter', to='companies.company')),
            ],
        ),
    ]
