# Generated by Django 5.1.15 on 2026-09-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_primary_company_one_primary_company'),
        ('notifications', '0003_minute_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='companies.company'),
        ),
    ]
