# Generated by Django 5.1.15 on 2026-09-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeesupervisor_employee_supervisors_signature_and_more'),
        ('notifications', '0004_meeting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='require_acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnnouncementReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.announcement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to='employees.employee')),
            ],
            options={
                'ordering': ['-acknowledged_at', '-seen_at'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'employee'), name='one_receipt_per_person_per_announcement')],
            },
        ),
    ]
