# Generated by Django 5.1.15 on 2026-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_announcement_audience_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12),
        ),
    ]
