# Generated by Django 5.1.15 on 2026-09-01 20:06

import django.db.models.deletion
import fieldvisits.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        ('expenses', '0002_expensebudget'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('inspection', 'Inspection'), ('supervision', 'Construction supervision'), ('survey', 'Survey / investigation'), ('maintenance', 'Maintenance'), ('emergency', 'Emergency response'), ('meeting', 'Meeting'), ('community', 'Community / stakeholder'), ('audit', 'Audit / regulatory'), ('training', 'Training'), ('other', 'Other')], default='inspection', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('description', models.TextField(blank=True, help_text='What the visit is for.')),
                ('report', models.TextField(blank=True)),
                ('transport', models.CharField(blank=True, max_length=120)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='For the travel order. The real figure comes from the expense claim.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits_to_approve', to='employees.employee')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='employees.employee')),
                ('expense_claim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visit', to='expenses.expenseclaim')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=fieldvisits.models.visit_attachment_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fieldvisits.fieldvisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visit_appearances', to='employees.employee')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='fieldvisits.fieldvisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['employee', 'starts_on'], name='fieldvisits_employe_2a18bf_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['status', 'starts_on'], name='fieldvisits_status_ae1c61_idx'),
        ),
    ]
