# Generated by Django 5.1.15 on 2026-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldvisits', '0002_site_fieldvisit_site_site_one_site_per_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='access_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='elevation_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sites/%Y/%m/'),
        ),
    ]
