# Generated by Django 5.1.15 on 2026-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldvisits', '0003_site_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvisit',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
