# Generated by Django 5.1.15 on 2026-08-31 11:17

import django.db.models.deletion
import mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent')], default='inbox', max_length=10)),
                ('uid', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=998)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to', models.TextField(blank=True)),
                ('cc', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['folder', '-date'], name='mail_emailm_folder_8c1133_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('uid', ''), _negated=True), fields=('folder', 'uid'), name='unique_folder_uid')],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=mail.models.attachment_upload_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.emailmessage')),
            ],
        ),
    ]
