# Generated by Django 5.1.15 on 2026-09-06 13:53

import django.db.models.deletion
import mail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_primary_company_one_primary_company'),
        ('employees', '0006_employeesupervisor_employee_supervisors_signature_and_more'),
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=60)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('received_on', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('from_office', models.CharField(max_length=300)),
                ('from_person', models.CharField(blank=True, max_length=200)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('received_via', models.CharField(choices=[('post', 'By post'), ('email', 'By email'), ('hand', 'By hand'), ('other', 'Other')], default='post', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_letters', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notify', models.ManyToManyField(blank=True, related_name='incoming_letters', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=60)),
                ('letter_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('addressed_to', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Not delivered'), ('not_emailed', 'Recorded, not emailed')], default='draft', max_length=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_letters', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-letter_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mail.models.letter_attachment_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.incomingletter')),
                ('outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.outgoingletter')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='incomingletter',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.outgoingletter'),
        ),
        migrations.AddConstraint(
            model_name='outgoingletter',
            constraint=models.UniqueConstraint(fields=('company', 'ref'), name='one_outgoing_ref_per_company'),
        ),
        migrations.AddConstraint(
            model_name='letterattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('incoming__isnull', True), ('outgoing__isnull', False)), models.Q(('incoming__isnull', False), ('outgoing__isnull', True)), _connector='OR'), name='attachment_belongs_to_one_letter'),
        ),
        migrations.AddConstraint(
            model_name='incomingletter',
            constraint=models.UniqueConstraint(fields=('company', 'ref'), name='one_incoming_ref_per_company'),
        ),
    ]
