# Generated by Django 5.1.15 on 2026-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_role',
            field=models.CharField(choices=[('manager', "Requester's Manager"), ('hr_admin', 'Any HR Admin'), ('supervisor', "Each of the requester's supervisors")], max_length=20),
        ),
    ]
