# Generated by Django 5.1.15 on 2026-08-31 11:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_device_id', models.CharField(max_length=100)),
                ('external_employee_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out')], max_length=20)),
                ('raw_timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-raw_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_web', models.BooleanField(default=True, help_text='Employees may clock in and out from the workspace.')),
                ('allow_biometric', models.BooleanField(default=True, help_text='Registered devices may post attendance for employees.')),
                ('lateness_deduction_enabled', models.BooleanField(default=False, help_text='Turn late arrivals into a pay deduction. Off unless a company chooses it.')),
                ('late_days_per_deduction', models.PositiveSmallIntegerField(default=3, help_text="How many late days cost one day's pay. Ignored while the deduction is off.")),
            ],
            options={
                'verbose_name_plural': 'Attendance policies',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web check-in'), ('manual', 'Manual (HR entry)'), ('biometric', 'Biometric device'), ('system', 'System (absence sweep)')], default='web', max_length=20)),
                ('note', models.CharField(blank=True, help_text="Optional — what this stretch was. 'Client visit', 'lunch'.", max_length=140)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('auto_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco'), ('hikvision', 'Hikvision'), ('generic', 'Generic / custom push')], default='generic', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='UTC', help_text='Olson name the device stamps its punches in, e.g. Asia/Kathmandu.', max_length=64)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('secret_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_web', models.BooleanField(blank=True, null=True)),
                ('allow_biometric', models.BooleanField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Why this person differs from the company default.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='Rate multiplier fixed at approval, so a later rate change cannot alter approved overtime.', max_digits=4, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegularisationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('requested_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('unpaid_break_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_night_shift', models.BooleanField(default=False, help_text='Attracts the night allowance below for each shift actually worked.')),
                ('night_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Paid once per night shift worked. Only applies when is_night_shift.', max_digits=12)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('check_in_time', 'Check-in time'), ('check_out_time', 'Check-out time'), ('status', 'Status')], max_length=30)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web check-in'), ('manual', 'Manual (HR entry)'), ('biometric', 'Biometric device'), ('system', 'System (absence sweep)')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
