# Generated by Django 5.1.15 on 2026-09-01 17:53

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, choices=[('travel', 'Travel'), ('meals', 'Meals'), ('supplies', 'Supplies'), ('software', 'Software'), ('training', 'Training'), ('other', 'Other')], help_text='Leave empty to cover every category.', max_length=20)),
                ('period', models.CharField(choices=[('fiscal_year', 'Fiscal year'), ('monthly', 'Month')], default='fiscal_year', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The pool for the period. 0 means no pool, cap only.', max_digits=14)),
                ('per_claim_cap', models.DecimalField(blank=True, decimal_places=2, help_text='The most one claim may be. Empty means no per-claim limit.', max_digits=12, null=True)),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=80, help_text='Warn once this percentage of the pool is committed. 0 = never.')),
                ('enforcement', models.CharField(choices=[('block', 'Refuse the claim'), ('warn', 'Allow, but flag it')], default='warn', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave empty to cover the whole company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='employees.department')),
                ('employee', models.ForeignKey(blank=True, help_text='For a personal allowance. Usually empty.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.comparison.Coalesce('department', models.Value(0)), django.db.models.functions.comparison.Coalesce('employee', models.Value(0)), models.F('category'), models.F('period'), name='unique_budget_scope')],
            },
        ),
    ]
