# Generated by Django 5.1.15 on 2026-09-01 14:58

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('legal_name', models.CharField(blank=True, help_text='As registered, if it differs from the name people use.', max_length=255)),
                ('kind', models.CharField(choices=[('parent', 'Parent / holding'), ('subsidiary', 'Subsidiary'), ('spv', 'Project company (SPV)'), ('jv', 'Joint venture'), ('branch', 'Branch office')], default='spv', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('pan_vat_number', models.CharField(blank=True, max_length=32, verbose_name='PAN / VAT')),
                ('licence_number', models.CharField(blank=True, max_length=64)),
                ('established_on', models.DateField(blank=True, null=True)),
                ('project_stage', models.CharField(choices=[('survey', 'Survey / feasibility'), ('licensed', 'Licensed, pre-construction'), ('construction', 'Under construction'), ('commissioning', 'Commissioning'), ('operation', 'In operation'), ('na', 'Not a project company')], default='na', max_length=20)),
                ('installed_capacity_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('river', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
