# Generated by Django 5.1.15 on 2026-09-02 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='The entity this installation runs payroll and other company-wide processes through. Exactly one company may be marked.'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='one_primary_company'),
        ),
    ]
