# Generated by Django 5.1.15 on 2026-09-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='primary_company',
            field=models.ForeignKey(blank=True, help_text='The company that employs this person. One, and it is the one that pays them.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_employees', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_companies',
            field=models.ManyToManyField(blank=True, help_text='Other group companies this person also works for. No payroll attaches to these.', related_name='secondary_employees', to='companies.company'),
        ),
    ]
