# Generated by Django 5.1.15 on 2026-09-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0003_employee_primary_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='On file for site emergencies.', max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Office cell'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Personal cell'),
        ),
        migrations.AddField(
            model_name='employee',
            name='temporary_address',
            field=models.CharField(blank=True, help_text='Current residence, if it differs.', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='kind',
            field=models.CharField(choices=[('previous', 'Previous employment'), ('internal', 'Held here')], default='previous', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('performance', 'Performance'), ('long_service', 'Long service'), ('safety', 'Safety'), ('innovation', 'Innovation'), ('teamwork', 'Teamwork'), ('other', 'Other')], default='other', max_length=20)),
                ('awarded_on', models.DateField()),
                ('awarded_by', models.CharField(blank=True, max_length=200)),
                ('citation', models.TextField(blank=True)),
                ('reward', models.CharField(blank=True, max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='employees/awards/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorporatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Seniority — 1 is the most senior. 0 means unranked and sorts last.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='corporate_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.corporatepost'),
        ),
        migrations.CreateModel(
            name='CorporateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_roles', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='corporate_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.corporaterole'),
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Leave empty for an indefinite suspension.', null=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('reinstated', 'Reinstated'), ('terminated', 'Ended in termination'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('outcome_note', models.TextField(blank=True)),
                ('lifted_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='employees.employee')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('verbal', 'Verbal warning'), ('written', 'Written warning'), ('final', 'Final warning'), ('suspension', 'Suspension'), ('demotion', 'Demotion'), ('dismissal', 'Dismissal')], default='verbal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('upheld', 'Upheld'), ('overturned', 'Overturned'), ('closed', 'Closed')], default='open', max_length=20)),
                ('incident_date', models.DateField()),
                ('issued_on', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('employee_response', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, help_text='After this date the action no longer counts against them.', null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/disciplinary/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suspension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_action', to='employees.suspension')),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
            },
        ),
    ]
