# Generated by Django 5.1.15 on 2026-09-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeesupervisor_employee_supervisors_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Signs for anybody in this department who has no supervisors of their own.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_departments', to='employees.employee'),
        ),
    ]
