# Generated by Django 5.1.15 on 2026-09-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='target_department',
            field=models.ForeignKey(blank=True, help_text='Which desk this is for. Chosen when the ticket is raised.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_tickets', to='employees.department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Also kept in the loop. Not handling it.', related_name='watched_tickets', to='employees.employee'),
        ),
    ]
