# Generated by Django 5.1.15 on 2026-09-01 19:59

import django.db.models.deletion
import memoranda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('memo_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('recommend', 'With a recommender'), ('approve', 'With the approver'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memoranda_to_approve', to='employees.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memoranda', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoranda_awaiting', to='employees.employee')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memoranda_initiated', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemorandumAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('effect', models.CharField(choices=[('proceed', 'Send it on'), ('return', 'Send it back')], default='proceed', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('for_approver', models.BooleanField(default=False, help_text='Also offered to the approver. Most recommendation words are not.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemorandumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=memoranda.models.memo_attachment_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='memoranda.memorandum')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MemorandumCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_serial', models.PositiveIntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo_counter', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('proceeded', 'Sent on'), ('returned', 'Sent back'), ('resubmitted', 'Sent forward again'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('commented', 'Commented')], max_length=20)),
                ('actor_label', models.CharField(blank=True, help_text='Who acted, as they were named at the time.', max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('action_label', models.CharField(blank=True, max_length=60)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memoranda.memorandumaction')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('actor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='memoranda.memorandum')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemorandumRecommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorandum_steps', to='employees.employee')),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommenders', to='memoranda.memorandum')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='memorandum',
            index=models.Index(fields=['current_holder', 'status'], name='memoranda_m_current_3b561e_idx'),
        ),
        migrations.AddIndex(
            model_name='memorandum',
            index=models.Index(fields=['initiator', 'status'], name='memoranda_m_initiat_e96ee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorandumrecommender',
            constraint=models.UniqueConstraint(fields=('memorandum', 'employee'), name='unique_memo_recommender'),
        ),
        migrations.AddConstraint(
            model_name='memorandumrecommender',
            constraint=models.UniqueConstraint(fields=('memorandum', 'order'), name='unique_memo_recommender_order'),
        ),
    ]
