# Generated by Django 5.1.15 on 2026-09-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_blood_group_employee_office_email_and_more'),
        ('memoranda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandumattachment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='memoranda.memorandumevent'),
        ),
        migrations.AddField(
            model_name='memorandumevent',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='memorandum_mentions', to='employees.employee'),
        ),
    ]
