# Generated by Django 5.1.15 on 2026-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoranda', '0003_skipped_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
