# Generated by Django 5.1.15 on 2026-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoranda', '0004_alter_memorandum_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandumevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('proceeded', 'Sent on'), ('returned', 'Sent back'), ('skipped', 'Skipped'), ('archived', 'Archived'), ('resubmitted', 'Sent forward again'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('commented', 'Commented')], max_length=20),
        ),
    ]
