# Generated by Django 5.1.15 on 2026-09-04 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeesupervisor_employee_supervisors_signature_and_more'),
        ('memoranda', '0005_archived_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorandumSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(default=0.62)),
                ('y', models.FloatField(default=0.78)),
                ('page', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorandum_signatures', to='employees.employee')),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='memoranda.memorandum')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='employees.signature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('memorandum', 'employee'), name='one_signature_per_person_per_memo')],
            },
        ),
    ]
